# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_Version',
            fields=[
                ('DB_id', models.AutoField(primary_key=True, serialize=False)),
                ('允许的最低版本', models.DecimalField(decimal_places=2, max_digits=12, null=True, unique=True)),
            ],
            options={
                'ordering': ['DB_id'],
                'db_table': 'TABEL_版本管理',
                'verbose_name': '版本管理表',
            },
        ),
    ]
