# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_table_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_Permission',
            fields=[
                ('DB_id', models.AutoField(primary_key=True, serialize=False)),
                ('用户名', models.CharField(max_length=100, unique=True)),
                ('查看数据概览', models.IntegerField(null=True)),
                ('查看单位信息', models.IntegerField(null=True)),
                ('查看立项信息', models.IntegerField(null=True)),
                ('查看招标信息', models.IntegerField(null=True)),
                ('查看合同信息', models.IntegerField(null=True)),
                ('查看预算信息', models.IntegerField(null=True)),
                ('查看付款信息', models.IntegerField(null=True)),
                ('查看变更信息', models.IntegerField(null=True)),
                ('查看分包合同信息', models.IntegerField(null=True)),
                ('操作单位信息', models.IntegerField(null=True)),
                ('允许操作立项的项目', models.CharField(max_length=100, null=True)),
                ('允许操作招标的项目', models.CharField(max_length=100, null=True)),
                ('允许操作合同的项目', models.CharField(max_length=100, null=True)),
                ('操作预算信息', models.IntegerField(null=True)),
                ('允许操作付款的项目', models.CharField(max_length=100, null=True)),
                ('允许操作变更的项目', models.CharField(max_length=100, null=True)),
                ('允许操作分包合同的项目', models.CharField(max_length=100, null=True)),
                ('允许调整概算的项目', models.CharField(max_length=100, null=True)),
                ('允许调整合同额的项目', models.CharField(max_length=100, null=True)),
                ('删除付款信息', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['DB_id'],
                'verbose_name': '权限信息表',
                'db_table': 'TABEL_权限信息',
            },
        ),
    ]
