# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_table_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_User',
            fields=[
                ('DB_id', models.AutoField(primary_key=True, serialize=False)),
                ('用户名', models.CharField(max_length=100, unique=True)),
                ('密码', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '用户表',
                'ordering': ['DB_id'],
                'db_table': 'TABEL_USER',
            },
        ),
    ]
