# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_table_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_Company',
            fields=[
                ('单位识别码', models.AutoField(primary_key=True, serialize=False)),
                ('单位名称', models.CharField(max_length=255, unique=True)),
                ('单位类别', models.CharField(max_length=255, null=True)),
                ('单位性质', models.CharField(max_length=255, null=True)),
                ('法定代表人', models.CharField(max_length=255, null=True)),
                ('注册资金', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('单位资质', models.CharField(max_length=255, null=True)),
                ('银行账号', models.CharField(max_length=255, null=True)),
                ('联系人', models.CharField(max_length=255, null=True)),
                ('联系方式', models.CharField(max_length=255, null=True)),
                ('单位备注', models.TextField(null=True)),
            ],
            options={
                'ordering': ['单位识别码'],
                'verbose_name': '单位信息表',
                'db_table': 'TABEL_单位信息',
            },
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许操作付款的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许操作分包合同的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许操作变更的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许操作合同的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许操作招标的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许操作立项的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许调整合同额的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='允许调整概算的项目',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='用户名',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='table_user',
            name='密码',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_user',
            name='用户名',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
