# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_auto_20171031_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_company',
            name='单位备注',
            field=models.TextField(max_length=65535, null=True),
        ),
    ]
