# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_auto_20171031_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_company',
            name='单位备注',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='删除付款信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='操作单位信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='操作预算信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看付款信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看分包合同信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看单位信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看变更信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看合同信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看招标信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看数据概览',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看立项信息',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='查看预算信息',
            field=models.SmallIntegerField(null=True),
        ),
    ]
