# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_auto_20171031_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_initiation',
            name='代建单位识别码',
            field=models.BigIntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='建设单位识别码',
            field=models.BigIntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='父项立项识别码',
            field=models.BigIntegerField(max_length=255, null=True),
        ),
    ]
