# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_auto_20171031_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_company',
            name='单位识别码',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='立项识别码',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_permission',
            name='DB_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_user',
            name='DB_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table_version',
            name='DB_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
