# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_auto_20171031_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_Bidding',
            fields=[
                ('招标识别码', models.BigAutoField(primary_key=True, serialize=False)),
                ('立项识别码', models.CharField(max_length=255, unique=True)),
                ('招标方式', models.CharField(max_length=255, null=True, unique=True)),
                ('招标单位识别码', models.BigIntegerField(max_length=255, null=True)),
                ('招标代理识别码', models.BigIntegerField(max_length=255, null=True)),
                ('预算控制价', models.BigIntegerField(max_length=255, null=True)),
                ('招标文件定稿时间', models.CharField(max_length=255, null=True)),
                ('公告邀请函发出时间', models.CharField(max_length=255, null=True)),
                ('开标时间', models.CharField(max_length=255, null=True)),
                ('中标通知书发出时间', models.CharField(max_length=255, null=True)),
                ('中标单位识别码', models.DateField()),
                ('中标价', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('招标备注', models.TextField(null=True)),
            ],
            options={
                'db_table': 'TABEL_招标信息',
                'ordering': ['招标识别码'],
                'verbose_name': '招标信息表',
            },
        ),
    ]
