# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_table_bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_bidding',
            name='中标单位识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='中标通知书发出时间',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='公告邀请函发出时间',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='开标时间',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='招标代理识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='招标单位识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='招标文件定稿时间',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='立项识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='预算控制价',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='代建单位识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='建设单位识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='父项立项识别码',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='立项时间',
            field=models.DateField(null=True),
        ),
    ]
