# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0013_auto_20171101_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_Contract',
            fields=[
                ('合同识别码', models.BigAutoField(primary_key=True, serialize=False)),
                ('立项识别码', models.BigIntegerField(null=True)),
                ('招标识别码', models.BigIntegerField(null=True)),
                ('合同编号', models.CharField(max_length=255, null=True, unique=True)),
                ('合同名称', models.CharField(max_length=255, null=True, unique=True)),
                ('合同主要内容', models.TextField(null=True)),
                ('合同类别', models.CharField(max_length=255, null=True, unique=True)),
                ('甲方识别码', models.BigIntegerField(null=True)),
                ('乙方识别码', models.BigIntegerField(null=True)),
                ('丙方识别码', models.BigIntegerField(null=True)),
                ('丁方识别码', models.BigIntegerField(null=True)),
                ('合同签订时间', models.DateField(null=True)),
                ('合同值_签订时', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('合同值_最新值', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('合同值_最终值', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('形象进度', models.CharField(max_length=255, null=True, unique=True)),
                ('支付上限', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('开工时间', models.DateField(null=True)),
                ('竣工合格时间', models.DateField(null=True)),
                ('保修结束时间', models.DateField(null=True)),
                ('审计完成时间', models.DateField(null=True)),
                ('合同备注', models.TextField(null=True)),
            ],
            options={
                'db_table': 'TABEL_合同信息',
                'ordering': ['合同识别码'],
                'verbose_name': '合同信息表',
            },
        ),
    ]
