# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0015_auto_20171101_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_initiation',
            name='立项简介',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='table_company',
            unique_together=set([('单位名称',)]),
        ),
        migrations.AlterModelTable(
            name='table_alteration',
            table='tabel_变更信息',
        ),
        migrations.AlterModelTable(
            name='table_bidding',
            table='tabel_招标信息',
        ),
        migrations.AlterModelTable(
            name='table_budget',
            table='tabel_预算信息',
        ),
        migrations.AlterModelTable(
            name='table_company',
            table='tabel_单位信息',
        ),
        migrations.AlterModelTable(
            name='table_contract',
            table='tabel_合同信息',
        ),
        migrations.AlterModelTable(
            name='table_initiation',
            table='tabel_立项信息',
        ),
        migrations.AlterModelTable(
            name='table_payment',
            table='tabel_付款信息',
        ),
        migrations.AlterModelTable(
            name='table_permission',
            table='tabel_权限信息',
        ),
        migrations.AlterModelTable(
            name='table_subcontract',
            table='tabel_分包合同信息',
        ),
        migrations.AlterModelTable(
            name='table_user',
            table='tabel_user',
        ),
        migrations.AlterModelTable(
            name='table_version',
            table='tabel_版本管理',
        ),
    ]
