# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0017_table_bidding_招标简介'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_initiation',
            name='分项名称',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_initiation',
            name='项目名称',
            field=models.CharField(max_length=255),
        ),
    ]
