# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0018_auto_20180331_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_alteration',
            name='变更主题',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_alteration',
            name='变更类型',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_bidding',
            name='招标方式',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_budget',
            name='预算周期',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_contract',
            name='合同名称',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_contract',
            name='合同类别',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_subcontract',
            name='分包合同主要内容',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_subcontract',
            name='分包合同名称',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table_subcontract',
            name='分包合同类别',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
